export const TableHeadData = [
  { id: 'username', label: 'Name' },
  { id: 'email', label: 'Email' },
  { id: 'role_id', label: 'Role' },
  { id: 'mobile_number', label: 'Mobile #' },
  { id: 'status', label: 'Status' },
  { id: '' },
];

export const ADD_SHIPMENT_INITIALS = {
  sender_name: '',
  sender_email: '',
  sender_phone: '',
  sender_address: '',
  sender_city: '',
  receiver_name: '',
  receiver_email: '',
  receiver_phone: '',
  receiver_address: '',
  receiver_city: '',
  total_quantity: 0,
  sub_total: 0,
  discount: 0,
  total_amount: 0,
  payment_type: '',
  payment_status: '',
  payment_date: '',
  status: '',
  orderItems: [],
};
