export const orders = [
  {
    id: 1,
    orderNumber: '#123123',
    trackingNumber: '#1233123',
    from: 'New York, USA',
    to: 'Karachi, Pakistan',
    fromUser: 'John',
    toUser: 'Doe',
    status: 'return_in_progrss',
  },
  {
    id: 2,
    orderNumber: '#2135566',
    trackingNumber: '#123156554',
    from: 'Lahore, Pakistan',
    to: 'Karachi, Pakistan',
    fromUser: 'Smith',
    toUser: 'Johnson',
    status: 'delivered',
  },
  {
    id: 3,
    orderNumber: '#123325632',
    trackingNumber: '#123183132',
    from: 'Karachi, Pakistan',
    to: 'Islamabad, Pakistan',
    fromUser: 'Williams',
    toUser: 'Miller',
    status: 'in_route',
  },
  {
    id: 4,
    orderNumber: '#123325632',
    trackingNumber: '#123183132',
    from: 'Islamabad, Pakistan',
    to: 'Multan, Pakistan',
    fromUser: 'Daniel',
    toUser: 'Christopher',
    status: 'in_process',
  },
  {
    id: 5,
    orderNumber: '#123325632',
    trackingNumber: '#123183132',
    from: 'Los Angles, USA',
    to: 'Islamabad, Pakistan',
    fromUser: 'Joseph',
    toUser: 'Rodriguez',
    status: 'cancelled',
  },
];

export const OrderTableHeadData = [
  { id: 'id', label: 'Id' },
  { id: 'orderNumber', label: 'Order Number' },
  { id: 'trackingNumber', label: 'Tracking Number' },
  { id: 'from', label: 'From Location' },
  { id: 'to', label: 'To Location' },
  { id: 'fromUser', label: 'From User' },
  { id: 'toUser', label: 'To User' },
  { id: 'status', label: 'Status' },
];
